# Generated by Django 4.0.4 on 2022-05-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='product_id',
            new_name='product',
        ),
    ]
