# Generated by Django 4.0.4 on 2022-05-23 12:22

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_category_id_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_images/",
                validators=[product.models.Product.validate_image],
            ),
        ),
    ]
