# Generated by Django 4.0.4 on 2022-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
