# Generated by Django 4.0.4 on 2022-05-23 13:21

from django.db import migrations, models
import norahs_ceramics.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_color_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subcategory",
            old_name="category_id",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=norahs_ceramics.fields.CaseInsensitiveCharField(
                max_length=200, unique=True
            ),
        ),
    ]
