# Generated by Django 4.0.4 on 2022-05-30 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_remove_product_category_product_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_pence",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(15000),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(max_length=500),
        ),
    ]
