# Generated by Django 4.0.4 on 2022-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_product_price_pence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.ManyToManyField(null=True, to="product.color"),
        ),
        migrations.DeleteModel(
            name="ProductColor",
        ),
    ]
